openapi: 3.2.0
info:
  description: 'This is a test to show how model refererence from another file are failing.

    This file is referenced api1.yaml.  If you load api1.yaml first in the browser it fails.

    However, if you load this file first, then load api1.yaml it will work.

    '
  version: 1.0.0
  title: API2 Test Test Api 2 API
tags:
- name: Test Api 2
paths:
  /test-api-2:
    get:
      summary: Api 2
      responses:
        '200':
          description: api 2 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestResponse2'
      tags:
      - Test Api 2
components:
  schemas:
    Api2Prop:
      type: string
      description: this is an api2prop
      example: api1prop-value
    TestResponse2:
      type: object
      description: This is a test prop
      properties:
        api2prop:
          $ref: '#/components/schemas/Api2Prop'
