openapi: 3.2.0
info:
  title: test doc Zero API
  description: 'test doc '
  license:
    name: Copyright @2018
  version: 1.0.0
servers:
- url: http://www.example.com/test/API
- url: https://www.example.com/test/API
tags:
- name: Zero
paths:
  /zero:
    post:
      parameters:
      - in: query
        name: one
        required: true
        schema:
          type: string
          enum:
          - 0
          - 1
      responses:
        200:
          description: response
          content:
            application/json:
              example:
                error: 0
      tags:
      - Zero
