openapi: 3.2.0
info:
  version: 0.0.1
  title: DDErl REST interface Sql API
  description: RESTful access to IMEM DB and DDErl
servers:
- url: /dderlrest/0.0.1
tags:
- name: sql
paths:
  /sql/:
    get:
      tags:
      - sql
      security:
      - basicAuth: []
      summary: execute sql
      operationId: execSql
      description: Prepare and execute SQL statements
      parameters:
      - name: x-irest-conn
        in: header
        required: false
        description: ErlImem connection identifier
        schema:
          type: string
      responses:
        '200':
          description: OK
          headers:
            x-irest-conn:
              description: ErlImem connection identifier
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
        '403':
          description: Malformed/Invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      readOnly: true
      type: object
      required:
      - errorCode
      - errorMessage
      - errorDetails
      properties:
        errorCode:
          description: Error Code
          type: number
          example: 1400
        errorMessage:
          description: Error Message
          type: string
          example: malformed
        errorDetails:
          description: Error Details
          type: string
          example: mandatory properties missing or bad type
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: HTTP Basic Authentication Username:Password
