openapi: 3.2.0
info:
  description: Test API
  version: '1.0'
  title: Test API with Schema API
  contact:
    name: Sample Person
    email: Sample.Person@adp.com
servers:
- url: https://__host__/
tags:
- name: Test API with Schema
  description: Test API with Schema
paths:
  /myApi:
    get:
      operationId: some guid
      responses:
        '200':
          description: Returns documents
      description: Returns documents
      tags:
      - Test API with Schema
      summary: Test API with Schema
